services:
  psql:
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - "./data:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: user
      POSTGRES_USER: postgres-user
      POSTGRES_PASSWORD: postgres-password
    restart: unless-stopped

  # pgadmin:
  #   image: dpage/pgadmin4:8.2
  #   ports:
  #     - "5050:80"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@example.com
  #     PGADMIN_DEFAULT_PASSWORD: admin-password
  #   restart: unless-stopped
  #   depends_on:
  #     - psql

  app:
    image: flashus/users
    build:
      context: .
      dockerfile: Dockerfile
    # build: .
    # command: ["/bin/sh", "-c", "ls /build/libs"]
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://psql:5432/user
      DB_USERNAME: postgres-user
      DB_PASSWORD: postgres-password
      PORT: 8080
    # restart: unless-stopped
    depends_on:
      - psql
