apiVersion: v1
kind: Namespace
metadata:
  name: idyachenko-users-dev

---
apiVersion: v1
kind: Namespace
metadata:
  name: idyachenko-users-test

---
apiVersion: v1
kind: Namespace
metadata:
  name: idyachenko-users-preprod

---
apiVersion: v1
kind: Namespace
metadata:
  name: idyachenko-users-production
