namespace: &namespace idyachenko-users-dev
appHost: idyachenko-users-dev.local

apps:
  backend:
    appName: users-backend
    namespace: *namespace
    replicasCount: 1
    container:
      version: v1.0.0

  db:
    appName: users-db
    namespace: *namespace
    replicasCount: 1
    container:
      version: 14

