spring:
  datasource:
    name: "integtest_users_application"
  jpa:
    hibernate.ddl-auto: validate
    show-sql: true
    generate-ddl: false
    properties:
      hibernate.dialect: "org.hibernate.dialect.PostgreSQLDialect"
      hibernate.current_session_context_class: "org.springframework.orm.hibernate5.SpringSessionContext"
      hibernate.connection.characterEncoding: "UTF-8"
      hibernate.connection.charSet: "UTF-8"
      hibernate.temp.use_jdbc_metadata_defaults: "true"
      hibernate.physical_naming_strategy: "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"
